-- ===============================================================
-- SISTEMA INTEGRAL DE GESTIÓN PARA BANQUETERÍA
-- Esquema + datos auxiliares + datos demo
-- Proyecto Capstone / APT
--
-- Diseñado a partir de:
-- 1) script.ddl original generado para Oracle Database 12c.
-- 2) modificaciones_script_base.sql.
-- 3) poblado_tablas_aux_v1.1.txt.
--
-- IMPORTANTE:
-- - Este script es para PostgreSQL, NO para Oracle.
-- - Ejecutar dentro de la base de datos ya creada, por ejemplo:
--   CREATE DATABASE sig_banqueteria;
--   \c sig_banqueteria
--   \i 01_bd_banqueteria_completa_postgresql.sql
-- ===============================================================

BEGIN;

-- ===============================================================
-- 0. LIMPIEZA PARA REEJECUCIÓN EN DESARROLLO
-- ===============================================================

DROP TABLE IF EXISTS auditoria CASCADE;
DROP TABLE IF EXISTS incidencia CASCADE;
DROP TABLE IF EXISTS checklist_montaje CASCADE;
DROP TABLE IF EXISTS pago CASCADE;
DROP TABLE IF EXISTS factura CASCADE;
DROP TABLE IF EXISTS venta CASCADE;
DROP TABLE IF EXISTS movimiento_inventario CASCADE;
DROP TABLE IF EXISTS inventario CASCADE;
DROP TABLE IF EXISTS bodega CASCADE;
DROP TABLE IF EXISTS cotizacion CASCADE;
DROP TABLE IF EXISTS detalle_pedido CASCADE;
DROP TABLE IF EXISTS detalle_preparacion CASCADE;
DROP TABLE IF EXISTS receta CASCADE;
DROP TABLE IF EXISTS ficha_tecnica CASCADE;
DROP TABLE IF EXISTS insumo CASCADE;
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS historial_pedido CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS evento CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS representante_legal CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS rol_permiso CASCADE;
DROP TABLE IF EXISTS permiso CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS parametro CASCADE;
DROP TABLE IF EXISTS estado_pedido CASCADE;
DROP TABLE IF EXISTS unidad CASCADE;
DROP TABLE IF EXISTS comuna CASCADE;
DROP TABLE IF EXISTS pais CASCADE;
DROP TABLE IF EXISTS region CASCADE;

-- ===============================================================
-- 1. COMPONENTE GEOGRÁFICO Y TABLAS AUXILIARES
--    Rescatado desde REGION, COMUNA, PAIS, UNIDAD y PARAMETRO.
-- ===============================================================

CREATE TABLE region (
    id_region INTEGER PRIMARY KEY,
    nombre_region VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE pais (
    id_pais INTEGER PRIMARY KEY,
    nombre_pais VARCHAR(120) NOT NULL UNIQUE,
    codigo_iso3 CHAR(3) NOT NULL UNIQUE
);

CREATE TABLE comuna (
    id_comuna INTEGER PRIMARY KEY,
    nombre_comuna VARCHAR(80) NOT NULL,
    id_region INTEGER NOT NULL REFERENCES region(id_region),
    UNIQUE (nombre_comuna, id_region)
);

CREATE TABLE unidad (
    id_unidad INTEGER PRIMARY KEY,
    nombre_unidad VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE parametro (
    id_parametro INTEGER PRIMARY KEY,
    nombre_parametro VARCHAR(60) NOT NULL UNIQUE,
    valor_numerico NUMERIC(12,2),
    valor_texto VARCHAR(200),
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo'
);

CREATE TABLE estado_pedido (
    id_estado_pedido INTEGER PRIMARY KEY,
    nombre_estado VARCHAR(40) NOT NULL UNIQUE,
    descripcion TEXT,
    orden INTEGER NOT NULL
);

-- ===============================================================
-- 2. COMPONENTE DE SEGURIDAD, ROLES, PERMISOS Y USUARIOS
--    Adapta PERFIL/USUARIA del modelo original hacia RBAC simple.
-- ===============================================================

CREATE TABLE rol (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(80) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permiso (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso VARCHAR(100) NOT NULL UNIQUE,
    modulo VARCHAR(80) NOT NULL,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo'
);

CREATE TABLE rol_permiso (
    id_rol INTEGER NOT NULL REFERENCES rol(id_rol) ON DELETE CASCADE,
    id_permiso INTEGER NOT NULL REFERENCES permiso(id_permiso) ON DELETE CASCADE,
    PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100),
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    telefono VARCHAR(30),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    ultimo_acceso TIMESTAMP,
    id_rol INTEGER NOT NULL REFERENCES rol(id_rol),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===============================================================
-- 3. COMPONENTE CLIENTES Y EVENTOS
--    Adapta CLIENTA y REP_LEGAL; agrega EVENTO requerido por el proyecto.
-- ===============================================================

CREATE TABLE representante_legal (
    id_representante_legal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR(20),
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100),
    email VARCHAR(150),
    telefono VARCHAR(30),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo'
);

CREATE TABLE cliente (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR(20),
    tipo_cliente VARCHAR(40) NOT NULL DEFAULT 'persona_natural',
    nombre VARCHAR(150) NOT NULL,
    apellido VARCHAR(100),
    nombre_fantasia VARCHAR(150),
    giro VARCHAR(200),
    email VARCHAR(150),
    telefono VARCHAR(30),
    direccion TEXT,
    id_comuna INTEGER REFERENCES comuna(id_comuna),
    id_pais INTEGER REFERENCES pais(id_pais),
    id_representante_legal INTEGER REFERENCES representante_legal(id_representante_legal),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE evento (
    id_evento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_evento VARCHAR(150) NOT NULL,
    fecha_evento DATE NOT NULL,
    hora_evento TIME,
    direccion TEXT NOT NULL,
    cantidad_personas INTEGER CHECK (cantidad_personas IS NULL OR cantidad_personas > 0),
    observaciones TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'planificado',
    id_cliente INTEGER NOT NULL REFERENCES cliente(id_cliente),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===============================================================
-- 4. COMPONENTE PEDIDOS Y TRAZABILIDAD
--    Adapta PEDIDO, DETALLE_PEDIDO y ESTADO_PEDIDO.
-- ===============================================================

CREATE TABLE pedido (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido VARCHAR(30) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_compromiso DATE,
    fecha_entrega DATE,
    observaciones TEXT,
    costo_estimado NUMERIC(12,2) NOT NULL DEFAULT 0,
    margen_objetivo NUMERIC(5,2) NOT NULL DEFAULT 0,
    precio_estimado NUMERIC(12,2) NOT NULL DEFAULT 0,
    id_cliente INTEGER NOT NULL REFERENCES cliente(id_cliente),
    id_evento INTEGER REFERENCES evento(id_evento),
    id_estado_pedido INTEGER NOT NULL REFERENCES estado_pedido(id_estado_pedido),
    id_usuario_responsable INTEGER REFERENCES usuario(id_usuario),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE historial_pedido (
    id_historial_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    id_estado_anterior INTEGER REFERENCES estado_pedido(id_estado_pedido),
    id_estado_nuevo INTEGER NOT NULL REFERENCES estado_pedido(id_estado_pedido),
    observacion TEXT,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    fecha_cambio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===============================================================
-- 5. COMPONENTE PRODUCCIÓN: PROVEEDORES, INSUMOS, FICHAS Y RECETAS
--    Adapta PROVEEDORA, ITEM, FT, DETALLE_INGREDIENTE y DETALLE_PREPARACION.
-- ===============================================================

CREATE TABLE proveedor (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_proveedor VARCHAR(150) NOT NULL,
    rut VARCHAR(20),
    nombre_contacto VARCHAR(100),
    email VARCHAR(150),
    telefono VARCHAR(30),
    direccion TEXT,
    id_comuna INTEGER REFERENCES comuna(id_comuna),
    id_pais INTEGER REFERENCES pais(id_pais),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE insumo (
    id_insumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_insumo VARCHAR(150) NOT NULL,
    descripcion TEXT,
    categoria VARCHAR(60),
    id_unidad INTEGER NOT NULL REFERENCES unidad(id_unidad),
    costo_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
    stock_minimo NUMERIC(12,3) NOT NULL DEFAULT 0,
    codigo_qr VARCHAR(120) UNIQUE,
    id_proveedor INTEGER REFERENCES proveedor(id_proveedor),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ficha_tecnica (
    id_ficha_tecnica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ficha VARCHAR(150) NOT NULL,
    descripcion TEXT,
    tipo_preparacion VARCHAR(80),
    rendimiento NUMERIC(12,3) NOT NULL DEFAULT 1,
    id_unidad_rendimiento INTEGER REFERENCES unidad(id_unidad),
    costo_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    precio_sugerido NUMERIC(12,2) NOT NULL DEFAULT 0,
    margen_objetivo NUMERIC(5,2) NOT NULL DEFAULT 0,
    imagen_url TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE receta (
    id_receta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ficha_tecnica INTEGER NOT NULL REFERENCES ficha_tecnica(id_ficha_tecnica) ON DELETE CASCADE,
    id_insumo INTEGER NOT NULL REFERENCES insumo(id_insumo),
    cantidad NUMERIC(12,3) NOT NULL CHECK (cantidad > 0),
    id_unidad INTEGER NOT NULL REFERENCES unidad(id_unidad),
    costo_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
    costo_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    observacion TEXT,
    UNIQUE (id_ficha_tecnica, id_insumo)
);

CREATE TABLE detalle_preparacion (
    id_detalle_preparacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ficha_tecnica INTEGER NOT NULL REFERENCES ficha_tecnica(id_ficha_tecnica) ON DELETE CASCADE,
    orden INTEGER NOT NULL DEFAULT 1,
    instruccion TEXT NOT NULL
);

CREATE TABLE detalle_pedido (
    id_detalle_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    tipo_detalle VARCHAR(30) NOT NULL DEFAULT 'ficha_tecnica',
    id_ficha_tecnica INTEGER REFERENCES ficha_tecnica(id_ficha_tecnica),
    id_insumo INTEGER REFERENCES insumo(id_insumo),
    descripcion_manual VARCHAR(200),
    cantidad NUMERIC(12,3) NOT NULL CHECK (cantidad > 0),
    costo_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
    precio_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12,2) GENERATED ALWAYS AS (ROUND((cantidad * precio_unitario)::numeric, 2)) STORED,
    CHECK (
        id_ficha_tecnica IS NOT NULL
        OR id_insumo IS NOT NULL
        OR descripcion_manual IS NOT NULL
    )
);

-- ===============================================================
-- 6. COMPONENTE COTIZACIÓN AUTOMÁTICA DE COSTOS Y MARGEN
-- ===============================================================

CREATE TABLE cotizacion (
    id_cotizacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    fecha_cotizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    costo_insumos NUMERIC(12,2) NOT NULL DEFAULT 0,
    costo_personal NUMERIC(12,2) NOT NULL DEFAULT 0,
    costo_transporte NUMERIC(12,2) NOT NULL DEFAULT 0,
    otros_costos NUMERIC(12,2) NOT NULL DEFAULT 0,
    costo_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    margen_objetivo NUMERIC(5,2) NOT NULL DEFAULT 0,
    precio_sugerido NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado VARCHAR(30) NOT NULL DEFAULT 'vigente',
    observacion TEXT,
    id_usuario INTEGER REFERENCES usuario(id_usuario)
);

-- ===============================================================
-- 7. COMPONENTE INVENTARIO, BODEGAS, QR Y MOVIMIENTOS
--    Reemplaza ENTRADA/SALIDA por MOVIMIENTO_INVENTARIO.
-- ===============================================================

CREATE TABLE bodega (
    id_bodega INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_bodega VARCHAR(150) NOT NULL,
    direccion TEXT,
    tipo_bodega VARCHAR(60),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo'
);

CREATE TABLE inventario (
    id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_insumo INTEGER NOT NULL REFERENCES insumo(id_insumo),
    id_bodega INTEGER NOT NULL REFERENCES bodega(id_bodega),
    stock_actual NUMERIC(12,3) NOT NULL DEFAULT 0,
    stock_minimo NUMERIC(12,3) NOT NULL DEFAULT 0,
    ubicacion VARCHAR(150),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    UNIQUE (id_insumo, id_bodega)
);

CREATE TABLE movimiento_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_movimiento VARCHAR(30) NOT NULL CHECK (tipo_movimiento IN ('entrada', 'salida', 'consumo', 'ajuste')),
    fecha_movimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cantidad NUMERIC(12,3) NOT NULL CHECK (cantidad > 0),
    costo_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
    observacion TEXT,
    id_insumo INTEGER NOT NULL REFERENCES insumo(id_insumo),
    id_bodega INTEGER NOT NULL REFERENCES bodega(id_bodega),
    id_pedido INTEGER REFERENCES pedido(id_pedido),
    id_usuario INTEGER REFERENCES usuario(id_usuario)
);

-- ===============================================================
-- 8. COMPONENTE VENTAS, FACTURACIÓN INTERNA Y PAGOS
--    No integra SII; registra facturación interna para MVP.
-- ===============================================================

CREATE TABLE venta (
    id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedido(id_pedido),
    fecha_venta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado VARCHAR(30) NOT NULL DEFAULT 'registrada',
    observacion TEXT
);

CREATE TABLE factura (
    id_factura INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL REFERENCES venta(id_venta) ON DELETE CASCADE,
    numero_factura VARCHAR(50),
    fecha_emision DATE NOT NULL DEFAULT CURRENT_DATE,
    monto_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado VARCHAR(30) NOT NULL DEFAULT 'emitida',
    observacion TEXT
);

CREATE TABLE pago (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura INTEGER NOT NULL REFERENCES factura(id_factura) ON DELETE CASCADE,
    fecha_pago DATE NOT NULL DEFAULT CURRENT_DATE,
    monto NUMERIC(12,2) NOT NULL CHECK (monto >= 0),
    metodo_pago VARCHAR(50),
    estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
    observacion TEXT
);

-- ===============================================================
-- 9. COMPONENTE OPERACIÓN EN TERRENO / APP MÓVIL
-- ===============================================================

CREATE TABLE checklist_montaje (
    id_checklist INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    item VARCHAR(200) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
    observaciones TEXT,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    fecha_actualizacion TIMESTAMP
);

CREATE TABLE incidencia (
    id_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    descripcion TEXT NOT NULL,
    foto_url TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'abierta',
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===============================================================
-- 10. COMPONENTE AUDITORÍA Y TRAZABILIDAD TRANSVERSAL
-- ===============================================================

CREATE TABLE auditoria (
    id_auditoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    modulo VARCHAR(80) NOT NULL,
    accion VARCHAR(100) NOT NULL,
    tabla_afectada VARCHAR(80),
    id_registro_afectado INTEGER,
    descripcion TEXT,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_origen VARCHAR(60)
);

-- ===============================================================
-- 11. ÍNDICES RECOMENDADOS
-- ===============================================================

CREATE INDEX idx_cliente_rut ON cliente(rut);
CREATE INDEX idx_evento_fecha ON evento(fecha_evento);
CREATE INDEX idx_pedido_estado ON pedido(id_estado_pedido);
CREATE INDEX idx_pedido_cliente ON pedido(id_cliente);
CREATE INDEX idx_pedido_evento ON pedido(id_evento);
CREATE INDEX idx_insumo_qr ON insumo(codigo_qr);
CREATE INDEX idx_mov_inv_insumo_fecha ON movimiento_inventario(id_insumo, fecha_movimiento);
CREATE INDEX idx_auditoria_fecha ON auditoria(fecha_hora);
CREATE INDEX idx_auditoria_modulo ON auditoria(modulo);

-- ===============================================================
-- 12. FUNCIÓN Y TRIGGERS PARA UPDATED_AT
-- ===============================================================

CREATE OR REPLACE FUNCTION actualizar_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_rol_updated_at
BEFORE UPDATE ON rol
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_usuario_updated_at
BEFORE UPDATE ON usuario
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_cliente_updated_at
BEFORE UPDATE ON cliente
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_evento_updated_at
BEFORE UPDATE ON evento
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_pedido_updated_at
BEFORE UPDATE ON pedido
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_proveedor_updated_at
BEFORE UPDATE ON proveedor
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_insumo_updated_at
BEFORE UPDATE ON insumo
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_ficha_tecnica_updated_at
BEFORE UPDATE ON ficha_tecnica
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

-- ===============================================================
-- 13. POBLADO AUXILIAR RESCATADO Y ADAPTADO
-- ===============================================================


INSERT INTO region (id_region, nombre_region) VALUES (1, 'TARAPACÁ');
INSERT INTO region (id_region, nombre_region) VALUES (2, 'ANTOFAGASTA');
INSERT INTO region (id_region, nombre_region) VALUES (3, 'ATACAMA');
INSERT INTO region (id_region, nombre_region) VALUES (4, 'COQUIMBO');
INSERT INTO region (id_region, nombre_region) VALUES (5, 'VALPARAÍSO');
INSERT INTO region (id_region, nombre_region) VALUES (6, 'OHIGGINS');
INSERT INTO region (id_region, nombre_region) VALUES (7, 'MAULE');
INSERT INTO region (id_region, nombre_region) VALUES (8, 'BIOBÍO');
INSERT INTO region (id_region, nombre_region) VALUES (9, 'ARAUCANÍA');
INSERT INTO region (id_region, nombre_region) VALUES (10, 'LOS LAGOS');
INSERT INTO region (id_region, nombre_region) VALUES (11, 'AYSÉN');
INSERT INTO region (id_region, nombre_region) VALUES (12, 'MAGALLANES Y ANTÁRTICA');
INSERT INTO region (id_region, nombre_region) VALUES (13, 'METROPOLITANA');
INSERT INTO region (id_region, nombre_region) VALUES (14, 'LOS RÍOS');
INSERT INTO region (id_region, nombre_region) VALUES (15, 'ARICA Y PARINACOTA');
INSERT INTO region (id_region, nombre_region) VALUES (16, 'ÑUBLE');
INSERT INTO region (id_region, nombre_region) VALUES (99, 'INTERNACIONAL');

INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (1, 'Afganistán', 'AFG');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (2, 'Albania', 'ALB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (3, 'Alemania', 'DEU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (4, 'Andorra', 'AND');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (5, 'Angola', 'AGO');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (6, 'Anguila', 'AIA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (7, 'Antártida', 'ATA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (8, 'Antigua y Barbuda', 'ATG');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (9, 'Arabia Saudita', 'SAU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (10, 'Argelia', 'DZA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (11, 'Argentina', 'ARG');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (12, 'Armenia', 'ARM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (13, 'Aruba', 'ABW');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (14, 'Australia', 'AUS');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (15, 'Austria', 'AUT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (16, 'Azerbaiyán', 'AZE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (17, 'Bahamas', 'BHS');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (18, 'Bahrein', 'BHR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (19, 'Bailía de Guernsey', 'GGY');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (20, 'Bangladesh', 'BGD');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (21, 'Barbados', 'BRB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (22, 'Belarús', 'BLR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (23, 'Bélgica', 'BEL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (24, 'Belice', 'BLZ');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (25, 'Benín', 'BEN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (26, 'Bermudas', 'BMU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (27, 'Bolivia', 'BOL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (28, 'Bosnia y Hercegovina', 'BIH');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (29, 'Botsuana', 'BWA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (30, 'Brasil', 'BRA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (31, 'Brunéi', 'BRN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (32, 'Bulgaria', 'BGR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (33, 'Burkina Faso', 'BFA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (34, 'Burundi', 'BDI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (35, 'Bután', 'BTN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (36, 'Cabo Verde', 'CPV');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (37, 'Camboya', 'KHM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (38, 'Camerún', 'CMR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (39, 'Canadá', 'CAN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (40, 'Caribe Neerlandés', 'BES');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (41, 'Catar', 'QAT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (42, 'Chad', 'TCD');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (43, 'Chequia', 'CZE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (44, 'Chile', 'CHL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (45, 'China', 'CHN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (46, 'Chipre', 'CYP');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (47, 'Ciudad del Vaticano', 'VAT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (48, 'Colombia', 'COL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (49, 'Comores', 'COM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (50, 'Corea del Norte', 'PRK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (51, 'Corea del Sur', 'KOR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (52, 'Costa de Marfil', 'CIV');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (53, 'Costa Rica', 'CRI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (54, 'Croacia', 'HRV');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (55, 'Cuba', 'CUB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (56, 'Curaçao', 'CUW');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (57, 'Dinamarca', 'DNK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (58, 'Dominica', 'DMA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (59, 'Ecuador', 'ECU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (60, 'Egipto', 'EGY');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (61, 'El Salvador', 'SLV');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (62, 'Emiratos Árabes Unidos', 'ARE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (63, 'Eritrea', 'ERI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (64, 'Eslovaquia', 'SVK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (65, 'Eslovenia', 'SVN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (66, 'España', 'ESP');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (67, 'Estados Federados de Micronesia', 'FSM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (68, 'Estados Unidos de América', 'USA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (69, 'Estonia', 'EST');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (70, 'Esuatini', 'SWZ');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (71, 'Etiopía', 'ETH');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (72, 'Filipinas', 'PHL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (73, 'Finlandia', 'FIN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (74, 'Fiyi', 'FJI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (75, 'Francia', 'FRA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (76, 'Gabón', 'GAB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (77, 'Gambia', 'GMB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (78, 'Georgia', 'GEO');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (79, 'Georgia del Sur y las Islas Sandwich del Sur', 'SGS');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (80, 'Ghana', 'GHA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (81, 'Gibraltar', 'GIB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (82, 'Granada', 'GRD');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (83, 'Grecia', 'GRC');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (84, 'Groenlandia', 'GRL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (85, 'Guadalupe', 'GLP');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (86, 'Guam', 'GUM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (87, 'Guatemala', 'GTM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (88, 'Guayana', 'GUY');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (89, 'Guayana Francesa', 'GUF');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (90, 'Guinea', 'GIN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (91, 'Guinea Ecuatorial', 'GNQ');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (92, 'Guinea-Bissau', 'GNB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (93, 'Haití', 'HTI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (94, 'Honduras', 'HND');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (95, 'Hong Kong', 'HKG');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (96, 'Hungría', 'HUN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (97, 'India', 'IND');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (98, 'Indonesia', 'IDN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (99, 'Irán', 'IRN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (100, 'Iraq', 'IRQ');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (101, 'Irlanda', 'IRL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (102, 'Isla Bouvet', 'BVT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (103, 'Isla de Man', 'IMN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (104, 'Isla de Navidad', 'CXR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (105, 'Isla de San Martín', 'MAF');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (106, 'Isla Mauricio', 'MUS');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (107, 'Isla Norfolk', 'NFK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (108, 'Islandia', 'ISL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (109, 'Islas Åland', 'ALA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (110, 'Islas Caimán', 'CYM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (111, 'Islas Cocos', 'CCK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (112, 'Islas Cook', 'COK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (113, 'Islas Feroe', 'FRO');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (114, 'Islas Heard y McDonald', 'HMD');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (115, 'Islas Malvinas', 'FLK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (116, 'Islas Marianas del Norte', 'MNP');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (117, 'Islas Marshall', 'MHL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (118, 'Islas Pitcairn', 'PCN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (119, 'Islas Salomón', 'SLB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (120, 'Islas Turcas y Caicos', 'TCA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (121, 'Islas ultramarinas menores de los Estados Unidos', 'UMI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (122, 'Islas Vírgenes (UK)', 'VGB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (123, 'Islas Vírgenes Americanas', 'VIR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (124, 'Israel', 'ISR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (125, 'Italia', 'ITA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (126, 'Jamaica', 'JAM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (127, 'Japón', 'JPN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (128, 'Jersey', 'JEY');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (129, 'Jordania', 'JOR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (130, 'Kazajistán​​​', 'KAZ');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (131, 'Kenia', 'KEN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (132, 'Kirguistán', 'KGZ');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (133, 'Kiribati', 'KIR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (134, 'Kosovo', 'XKX');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (135, 'Kuwait', 'KWT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (136, 'Laos', 'LAO');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (137, 'Lesotho', 'LSO');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (138, 'Letonia', 'LVA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (139, 'Líbano', 'LBN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (140, 'Liberia', 'LBR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (141, 'Libia', 'LBY');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (142, 'Liechtenstein', 'LIE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (143, 'Lituania', 'LTU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (144, 'Luxemburgo', 'LUX');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (145, 'Macao', 'MAC');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (146, 'Macedonia del Norte', 'MKD');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (147, 'Madagascar', 'MDG');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (148, 'Malasia', 'MYS');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (149, 'Malaui', 'MWI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (150, 'Maldivas', 'MDV');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (151, 'Malí', 'MLI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (152, 'Malta', 'MLT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (153, 'Marruecos', 'MAR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (154, 'Martinica', 'MTQ');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (155, 'Mauritania', 'MRT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (156, 'Mayotte', 'MYT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (157, 'México', 'MEX');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (158, 'Moldavia', 'MDA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (159, 'Mongolia', 'MNG');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (160, 'Montenegro', 'MNE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (161, 'Montserrat', 'MSR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (162, 'Mozambique', 'MOZ');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (163, 'Myanmar', 'MMR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (164, 'Namibia', 'NAM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (165, 'Nauru', 'NRU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (166, 'Nepal', 'NPL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (167, 'Nicaragua', 'NIC');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (168, 'Níger', 'NER');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (169, 'Nigeria', 'NGA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (170, 'Niue', 'NIU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (171, 'Noruega', 'NOR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (172, 'Nueva Caledonia', 'NCL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (173, 'Nueva Zelandia', 'NZL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (174, 'Omán', 'OMN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (175, 'Países Bajos', 'NLD');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (176, 'Pakistán', 'PAK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (177, 'Palaos', 'PLW');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (178, 'Palestina', 'PSE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (179, 'Panamá', 'PAN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (180, 'Papúa Nueva Guinea', 'PNG');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (181, 'Paraguay', 'PRY');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (182, 'Perú', 'PER');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (183, 'Polinesia Francesa', 'PYF');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (184, 'Polonia', 'POL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (185, 'Portugal', 'PRT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (186, 'Principado de Mónaco', 'MCO');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (187, 'Puerto Rico', 'PRI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (188, 'Reino Unido', 'GBR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (189, 'República Centroafricana', 'CAF');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (190, 'República del Congo', 'COG');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (191, 'República Democrática del Congo', 'COD');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (192, 'República Dominicana', 'DOM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (193, 'Reunión', 'REU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (194, 'Ruanda', 'RWA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (195, 'Rumania', 'ROU');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (196, 'Rusia', 'RUS');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (197, 'Sáhara Occidental', 'ESH');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (198, 'Samoa', 'WSM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (199, 'Samoa Americana', 'ASM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (200, 'San Bartolomé', 'BLM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (201, 'San Cristóbal y Nieves', 'KNA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (202, 'San Marino', 'SMR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (203, 'San Pedro y Miquelón', 'SPM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (204, 'San Vicente y las Granadinas', 'VCT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (205, 'Santa Elena, Ascensión y Tristán de Acuña', 'SHN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (206, 'Santa Lucía', 'LCA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (207, 'Santo Tomé y Príncipe', 'STP');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (208, 'Senegal', 'SEN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (209, 'Serbia', 'SRB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (210, 'Seychelles', 'SYC');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (211, 'Sierra Leona', 'SLE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (212, 'Singapur', 'SGP');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (213, 'Sint Maarten', 'SXM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (214, 'Siria', 'SYR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (215, 'Somalia', 'SOM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (216, 'Sri Lanka', 'LKA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (217, 'Sudáfrica', 'ZAF');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (218, 'Sudán', 'SDN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (219, 'Sudán del Sur', 'SSD');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (220, 'Suecia', 'SWE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (221, 'Suiza', 'CHE');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (222, 'Surinam', 'SUR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (223, 'Svalbard y Jan Mayen', 'SJM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (224, 'Tailandia', 'THA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (225, 'Taiwán', 'TWN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (226, 'Tanzania', 'TZA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (227, 'Tayikistán', 'TJK');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (228, 'Territorio Británico del Océano Índico', 'IOT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (229, 'Territorios Australes y Antárticos Franceses', 'ATF');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (230, 'Timor Oriental', 'TLS');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (231, 'Togo', 'TGO');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (232, 'Tokelau', 'TKL');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (233, 'Tonga', 'TON');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (234, 'Trinidad y Tobago', 'TTO');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (235, 'Túnez', 'TUN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (236, 'Turkmenistán', 'TKM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (237, 'Turquía', 'TUR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (238, 'Tuvalu', 'TUV');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (239, 'Ucrania', 'UKR');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (240, 'Uganda', 'UGA');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (241, 'Uruguay', 'URY');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (242, 'Uzbekistán', 'UZB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (243, 'Vanuatu', 'VUT');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (244, 'Venezuela', 'VEN');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (245, 'Vietnam', 'VNM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (246, 'Wallis y Futuna', 'WLF');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (247, 'Yemen', 'YEM');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (248, 'Yibuti', 'DJI');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (249, 'Zambia', 'ZMB');
INSERT INTO pais (id_pais, nombre_pais, codigo_iso3) VALUES (250, 'Zimbabue', 'ZWE');

INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (1, 'Arica', 15);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (2, 'Camarones', 15);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (3, 'Putre', 15);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (4, 'General Lagos', 15);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (5, 'Iquique', 1);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (6, 'Camiña', 1);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (7, 'Colchane', 1);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (8, 'Huara', 1);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (9, 'Pica', 1);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (10, 'Pozo Almonte', 1);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (11, 'Alto Hospicio', 1);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (12, 'Antofagasta', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (13, 'Mejillones', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (14, 'Sierra Gorda', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (15, 'Taltal', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (16, 'Calama', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (17, 'Ollagüe', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (18, 'San Pedro de Atacama', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (19, 'Tocopilla', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (20, 'María Elena', 2);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (21, 'Copiapó', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (22, 'Caldera', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (23, 'Tierra Amarilla', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (24, 'Chañaral', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (25, 'Diego de Almagro', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (26, 'Vallenar', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (27, 'Alto del Carmen', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (28, 'Freirina', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (29, 'Huasco', 3);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (30, 'La Serena', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (31, 'Coquimbo', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (32, 'Andacollo', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (33, 'La Higuera', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (34, 'Paiguano', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (35, 'Vicuña', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (36, 'Illapel', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (37, 'Canela', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (38, 'Los Vilos', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (39, 'Salamanca', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (40, 'Ovalle', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (41, 'Combarbalá', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (42, 'Monte Patria', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (43, 'Punitaqui', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (44, 'Río Hurtado', 4);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (45, 'Valparaíso', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (46, 'Casablanca', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (47, 'Concón', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (48, 'Juan Fernández', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (49, 'Puchuncaví', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (50, 'Quilpué', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (51, 'Quintero', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (52, 'Villa Alemana', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (53, 'Viña del Mar', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (54, 'Isla  de Pascua', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (55, 'Los Andes', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (56, 'Calle Larga', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (57, 'Rinconada', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (58, 'San Esteban', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (59, 'La Ligua', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (60, 'Cabildo', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (61, 'Papudo', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (62, 'Petorca', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (63, 'Zapallar', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (64, 'Quillota', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (65, 'Calera', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (66, 'Hijuelas', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (67, 'La Cruz', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (68, 'Limache', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (69, 'Nogales', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (70, 'Olmué', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (71, 'San Antonio', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (72, 'Algarrobo', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (73, 'Cartagena', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (74, 'El Quisco', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (75, 'El Tabo', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (76, 'Santo Domingo', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (77, 'San Felipe', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (78, 'Catemu', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (79, 'Llaillay', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (80, 'Panquehue', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (81, 'Putaendo', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (82, 'Santa María', 5);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (83, 'Rancagua', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (84, 'Codegua', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (85, 'Coinco', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (86, 'Coltauco', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (87, 'Doñihue', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (88, 'Graneros', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (89, 'Las Cabras', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (90, 'Machalí', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (91, 'Malloa', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (92, 'Mostazal', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (93, 'Olivar', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (94, 'Peumo', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (95, 'Pichidegua', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (96, 'Quinta de Tilcoco', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (97, 'Rengo', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (98, 'Requínoa', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (99, 'San Vicente', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (100, 'Pichilemu', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (101, 'La Estrella', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (102, 'Litueche', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (103, 'Marchihue', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (104, 'Navidad', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (105, 'Paredones', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (106, 'San Fernando', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (107, 'Chépica', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (108, 'Chimbarongo', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (109, 'Lolol', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (110, 'Nancagua', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (111, 'Palmilla', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (112, 'Peralillo', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (113, 'Placilla', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (114, 'Pumanque', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (115, 'Santa Cruz', 6);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (116, 'Talca', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (117, 'Constitución', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (118, 'Curepto', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (119, 'Empedrado', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (120, 'Maule', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (121, 'Pelarco', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (122, 'Pencahue', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (123, 'Río Claro', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (124, 'San Clemente', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (125, 'San Rafael', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (126, 'Cauquenes', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (127, 'Chanco', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (128, 'Pelluhue', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (129, 'Curicó', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (130, 'Hualañé', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (131, 'Licantén', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (132, 'Molina', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (133, 'Rauco', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (134, 'Romeral', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (135, 'Sagrada Familia', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (136, 'Teno', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (137, 'Vichuquén', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (138, 'Linares', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (139, 'Colbún', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (140, 'Longaví', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (141, 'Parral', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (142, 'Retiro', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (143, 'San Javier', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (144, 'Villa Alegre', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (145, 'Yerbas Buenas', 7);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (146, 'Concepción', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (147, 'Coronel', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (148, 'Chiguayante', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (149, 'Florida', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (150, 'Hualqui', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (151, 'Lota', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (152, 'Penco', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (153, 'San Pedro de la Paz', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (154, 'Santa Juana', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (155, 'Talcahuano', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (156, 'Tomé', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (157, 'Hualpén', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (158, 'Lebu', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (159, 'Arauco', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (160, 'Cañete', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (161, 'Contulmo', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (162, 'Curanilahue', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (163, 'Los Álamos', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (164, 'Tirúa', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (165, 'Los Ángeles', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (166, 'Antuco', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (167, 'Cabrero', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (168, 'Laja', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (169, 'Mulchén', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (170, 'Nacimiento', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (171, 'Negrete', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (172, 'Quilaco', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (173, 'Quilleco', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (174, 'San Rosendo', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (175, 'Santa Bárbara', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (176, 'Tucapel', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (177, 'Yumbel', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (178, 'Alto Biobío', 8);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (179, 'Chillán', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (180, 'Bulnes', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (181, 'Cobquecura', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (182, 'Coelemu', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (183, 'Coihueco', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (184, 'Chillán Viejo', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (185, 'El Carmen', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (186, 'Ninhue', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (187, 'Ñiquén', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (188, 'Pemuco', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (189, 'Pinto', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (190, 'Portezuelo', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (191, 'Quillón', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (192, 'Quirihue', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (193, 'Ránquil', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (194, 'San Carlos', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (195, 'San Fabián', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (196, 'San Ignacio', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (197, 'San Nicolás', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (198, 'Treguaco', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (199, 'Yungay', 16);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (200, 'Temuco', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (201, 'Carahue', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (202, 'Cunco', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (203, 'Curarrehue', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (204, 'Freire', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (205, 'Galvarino', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (206, 'Gorbea', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (207, 'Lautaro', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (208, 'Loncoche', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (209, 'Melipeuco', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (210, 'Nueva Imperial', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (211, 'Padre Las Casas', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (212, 'Perquenco', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (213, 'Pitrufquén', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (214, 'Pucón', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (215, 'Saavedra', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (216, 'Teodoro Schmidt', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (217, 'Toltén', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (218, 'Vilcún', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (219, 'Villarrica', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (220, 'Cholchol', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (221, 'Angol', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (222, 'Collipulli', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (223, 'Curacautín', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (224, 'Ercilla', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (225, 'Lonquimay', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (226, 'Los Sauces', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (227, 'Lumaco', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (228, 'Purén', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (229, 'Renaico', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (230, 'Traiguén', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (231, 'Victoria', 9);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (232, 'Valdivia', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (233, 'Corral', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (234, 'Futrono', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (235, 'La Unión', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (236, 'Lago Ranco', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (237, 'Lanco', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (238, 'Los Lagos', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (239, 'Máfil', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (240, 'Mariquina', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (241, 'Paillaco', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (242, 'Panguipulli', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (243, 'Río Bueno', 14);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (244, 'Puerto Montt', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (245, 'Calbuco', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (246, 'Cochamó', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (247, 'Fresia', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (248, 'Frutillar', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (249, 'Los Muermos', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (250, 'Llanquihue', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (251, 'Maullín', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (252, 'Puerto Varas', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (253, 'Castro', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (254, 'Ancud', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (255, 'Chonchi', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (256, 'Curaco de Vélez', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (257, 'Dalcahue', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (258, 'Puqueldón', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (259, 'Queilén', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (260, 'Quellón', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (261, 'Quemchi', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (262, 'Quinchao', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (263, 'Osorno', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (264, 'Puerto Octay', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (265, 'Purranque', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (266, 'Puyehue', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (267, 'Río Negro', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (268, 'San Juan de la Costa', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (269, 'San Pablo', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (270, 'Chaitén', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (271, 'Futaleufú', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (272, 'Hualaihué', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (273, 'Palena', 10);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (274, 'Coihaique', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (275, 'Lago Verde', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (276, 'Aisén', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (277, 'Cisnes', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (278, 'Guaitecas', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (279, 'Cochrane', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (280, 'OHiggins', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (281, 'Tortel', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (282, 'Chile Chico', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (283, 'Río Ibáñez', 11);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (284, 'Punta Arenas', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (285, 'Laguna Blanca', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (286, 'Río Verde', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (287, 'San Gregorio', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (288, 'Cabo de Hornos', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (289, 'Antártica', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (290, 'Porvenir', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (291, 'Primavera', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (292, 'Timaukel', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (293, 'Natales', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (294, 'Torres del Paine', 12);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (295, 'Santiago', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (296, 'Cerrillos', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (297, 'Cerro Navia', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (298, 'Conchalí', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (299, 'El Bosque', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (300, 'Estación Central', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (301, 'Huechuraba', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (302, 'Independencia', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (303, 'La Cisterna', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (304, 'La Florida', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (305, 'La Granja', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (306, 'La Pintana', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (307, 'La Reina', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (308, 'Las Condes', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (309, 'Lo Barnechea', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (310, 'Lo Espejo', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (311, 'Lo Prado', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (312, 'Macul', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (313, 'Maipú', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (314, 'Ñuñoa', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (315, 'Pedro Aguirre Cerda', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (316, 'Peñalolén', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (317, 'Providencia', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (318, 'Pudahuel', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (319, 'Quilicura', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (320, 'Quinta Normal', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (321, 'Recoleta', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (322, 'Renca', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (323, 'San Joaquín', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (324, 'San Miguel', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (325, 'San Ramón', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (326, 'Vitacura', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (327, 'Puente Alto', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (328, 'Pirque', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (329, 'San José de Maipo', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (330, 'Colina', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (331, 'Lampa', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (332, 'Tiltil', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (333, 'San Bernardo', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (334, 'Buin', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (335, 'Calera de Tango', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (336, 'Paine', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (337, 'Melipilla', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (338, 'Alhué', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (339, 'Curacaví', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (340, 'María Pinto', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (341, 'San Pedro', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (342, 'Talagante', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (343, 'El Monte', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (344, 'Isla de Maipo', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (345, 'Padre Hurtado', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (346, 'Peñaflor', 13);
INSERT INTO comuna (id_comuna, nombre_comuna, id_region) VALUES (999, 'Internacional', 99);

INSERT INTO unidad (id_unidad, nombre_unidad) VALUES (1, 'kg');
INSERT INTO unidad (id_unidad, nombre_unidad) VALUES (2, 'g');
INSERT INTO unidad (id_unidad, nombre_unidad) VALUES (3, 'lt');
INSERT INTO unidad (id_unidad, nombre_unidad) VALUES (4, 'ml');
INSERT INTO unidad (id_unidad, nombre_unidad) VALUES (5, 'unidades');
INSERT INTO unidad (id_unidad, nombre_unidad) VALUES (6, 'cda.');
INSERT INTO unidad (id_unidad, nombre_unidad) VALUES (7, 'cdta.');

INSERT INTO parametro (id_parametro, nombre_parametro, valor_numerico, descripcion) VALUES (1, 'PERIODO_COSTO', 90, 'Parámetro rescatado del script auxiliar original');
INSERT INTO parametro (id_parametro, nombre_parametro, valor_numerico, descripcion) VALUES (2, 'MARGEN_VTA', 30, 'Parámetro rescatado del script auxiliar original');

-- Estados adaptados al flujo del proyecto: creado -> confirmado -> preparación -> despachado -> finalizado.
INSERT INTO estado_pedido (id_estado_pedido, nombre_estado, descripcion, orden) VALUES
(1, 'CREADO', 'Pedido registrado inicialmente en el sistema.', 1),
(2, 'CONFIRMADO', 'Pedido confirmado para preparación y planificación.', 2),
(3, 'EN_PREPARACION', 'Pedido en proceso de producción o preparación.', 3),
(4, 'DESPACHADO', 'Pedido despachado hacia el evento.', 4),
(5, 'FINALIZADO', 'Pedido finalizado y listo para cierre de costos.', 5),
(6, 'CANCELADO', 'Pedido cancelado.', 6),
(7, 'RECHAZADO', 'Pedido rechazado o no aceptado.', 7);


-- Roles adaptados desde PERFIL y ampliados para el MVP web/móvil.
INSERT INTO rol (id_rol, nombre_rol, descripcion) VALUES
(1, 'ADMINISTRADOR', 'Acceso completo al sistema.'),
(2, 'VENTAS', 'Gestión comercial, clientes, eventos, pedidos y cotizaciones.'),
(3, 'COCINA', 'Gestión de fichas técnicas, recetas y preparación.'),
(4, 'LOGISTICA', 'Gestión de inventario, bodegas, movimientos y despacho.'),
(5, 'TERRENO', 'Uso de aplicación móvil para checklist, incidencias, estados y QR.');

INSERT INTO permiso (id_permiso, nombre_permiso, modulo, descripcion) VALUES
(1, 'usuarios.gestionar', 'usuarios', 'Crear, editar y deshabilitar usuarios.'),
(2, 'roles.gestionar', 'seguridad', 'Administrar roles y permisos.'),
(3, 'clientes.ver', 'clientes', 'Consultar clientes.'),
(4, 'clientes.gestionar', 'clientes', 'Crear y modificar clientes.'),
(5, 'eventos.ver', 'eventos', 'Consultar eventos.'),
(6, 'eventos.gestionar', 'eventos', 'Crear y modificar eventos.'),
(7, 'pedidos.ver', 'pedidos', 'Consultar pedidos.'),
(8, 'pedidos.gestionar', 'pedidos', 'Crear y modificar pedidos.'),
(9, 'pedidos.cambiar_estado', 'pedidos', 'Cambiar estado del pedido.'),
(10, 'fichas.ver', 'produccion', 'Consultar fichas técnicas.'),
(11, 'fichas.gestionar', 'produccion', 'Crear y modificar fichas técnicas y recetas.'),
(12, 'insumos.gestionar', 'produccion', 'Crear y modificar insumos.'),
(13, 'cotizaciones.gestionar', 'cotizacion', 'Crear y modificar cotizaciones.'),
(14, 'inventario.ver', 'inventario', 'Consultar inventario.'),
(15, 'inventario.gestionar', 'inventario', 'Registrar movimientos de inventario.'),
(16, 'ventas.gestionar', 'ventas', 'Registrar ventas, facturación interna y pagos.'),
(17, 'dashboard.ver', 'dashboard', 'Visualizar indicadores y reportes.'),
(18, 'movil.operar', 'movil', 'Usar funciones móviles de terreno.'),
(19, 'incidencias.gestionar', 'movil', 'Registrar y gestionar incidencias.'),
(20, 'auditoria.ver', 'auditoria', 'Consultar trazabilidad y auditoría.');

-- Administrador: todos los permisos.
INSERT INTO rol_permiso (id_rol, id_permiso)
SELECT 1, id_permiso FROM permiso;

-- Ventas.
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES
(2,3),(2,4),(2,5),(2,6),(2,7),(2,8),(2,13),(2,16),(2,17);

-- Cocina.
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES
(3,7),(3,9),(3,10),(3,11),(3,12),(3,14),(3,17);

-- Logística.
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES
(4,5),(4,7),(4,9),(4,14),(4,15),(4,17),(4,18),(4,19);

-- Terreno.
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES
(5,5),(5,7),(5,9),(5,14),(5,15),(5,18),(5,19);


-- ===============================================================
-- 14. POBLADO DEMO DEL NEGOCIO
--     Datos mínimos para que el sistema pueda probarse en frontend/backend.
-- ===============================================================

-- Usuario administrador de prueba.
-- Reemplazar password_hash por un hash real generado con bcrypt desde el backend.
INSERT INTO usuario (id_usuario, nombre, apellido, email, password_hash, telefono, id_rol)
VALUES (1, 'Administrador', 'Sistema', 'admin@banqueteria.cl', 'REEMPLAZAR_POR_HASH_BCRYPT', '+56912345678', 1);

INSERT INTO representante_legal (id_representante_legal, rut, nombre, apellido, email, telefono)
VALUES (1, '11.111.111-1', 'Carolina', 'Pérez', 'carolina.perez@cliente.cl', '+56911111111');

INSERT INTO cliente (id_cliente, rut, tipo_cliente, nombre, apellido, nombre_fantasia, giro, email, telefono, direccion, id_comuna, id_pais, id_representante_legal)
VALUES
(1, '12.345.678-9', 'persona_natural', 'Camila', 'Duarte', NULL, NULL, 'camila.duarte@correo.cl', '+56922222222', 'Cerro Navia, Santiago', 297, 44, NULL),
(2, '76.000.000-1', 'empresa', 'Empresa Eventos Maya', NULL, 'Eventos Maya', 'Servicios de eventos', 'contacto@mayaeventos.cl', '+56222222222', 'Santiago Centro', 295, 44, 1);

INSERT INTO evento (id_evento, nombre_evento, fecha_evento, hora_evento, direccion, cantidad_personas, observaciones, id_cliente)
VALUES
(1, 'Cumpleaños familiar', CURRENT_DATE + 20, '18:00', 'Cerro Navia, Santiago', 60, 'Servicio tipo cocktail.', 1),
(2, 'Cena empresa', CURRENT_DATE + 30, '20:00', 'Santiago Centro', 120, 'Evento corporativo.', 2);

INSERT INTO proveedor (id_proveedor, nombre_proveedor, rut, nombre_contacto, email, telefono, direccion, id_comuna, id_pais)
VALUES
(1, 'Distribuidora Alimentos Centro', '77.111.111-1', 'Luis Soto', 'ventas@alimentoscentro.cl', '+56223334444', 'Santiago', 295, 44),
(2, 'Verduras y Frutas La Vega', '77.222.222-2', 'María Rojas', 'contacto@lavega.cl', '+56224445555', 'Recoleta', 321, 44);

INSERT INTO insumo (id_insumo, nombre_insumo, descripcion, categoria, id_unidad, costo_unitario, stock_minimo, codigo_qr, id_proveedor)
VALUES
(1, 'Arroz', 'Arroz grano largo', 'abarrotes', 1, 1200, 10, 'INS-ARROZ-001', 1),
(2, 'Pollo', 'Pollo deshuesado', 'carnes', 1, 4500, 8, 'INS-POLLO-001', 1),
(3, 'Lechuga', 'Lechuga fresca', 'verduras', 5, 900, 20, 'INS-LECHUGA-001', 2),
(4, 'Bebida 1.5L', 'Bebida desechable', 'bebestibles', 5, 1300, 30, 'INS-BEBIDA-001', 1);

INSERT INTO ficha_tecnica (id_ficha_tecnica, nombre_ficha, descripcion, tipo_preparacion, rendimiento, id_unidad_rendimiento, costo_total, precio_sugerido, margen_objetivo, imagen_url)
VALUES
(1, 'Arroz con pollo', 'Preparación principal para eventos familiares.', 'plato_fondo', 10, 5, 57000, 85000, 30, NULL),
(2, 'Ensalada verde', 'Acompañamiento fresco.', 'acompanamiento', 10, 5, 18000, 28000, 30, NULL);

INSERT INTO receta (id_receta, id_ficha_tecnica, id_insumo, cantidad, id_unidad, costo_unitario, costo_total)
VALUES
(1, 1, 1, 3.000, 1, 1200, 3600),
(2, 1, 2, 10.000, 1, 4500, 45000),
(3, 2, 3, 10.000, 5, 900, 9000);

INSERT INTO detalle_preparacion (id_detalle_preparacion, id_ficha_tecnica, orden, instruccion)
VALUES
(1, 1, 1, 'Preparar arroz según cantidad de porciones.'),
(2, 1, 2, 'Cocinar pollo y mantener cadena de temperatura.'),
(3, 2, 1, 'Lavar, sanitizar y porcionar verduras.');

INSERT INTO bodega (id_bodega, nombre_bodega, direccion, tipo_bodega)
VALUES (1, 'Bodega Central', 'Santiago', 'principal');

INSERT INTO inventario (id_inventario, id_insumo, id_bodega, stock_actual, stock_minimo, ubicacion)
VALUES
(1, 1, 1, 25, 10, 'Estante A1'),
(2, 2, 1, 8, 8, 'Refrigerador 1'),
(3, 3, 1, 40, 20, 'Zona verduras'),
(4, 4, 1, 60, 30, 'Estante bebidas');

INSERT INTO movimiento_inventario (id_movimiento, tipo_movimiento, cantidad, costo_unitario, observacion, id_insumo, id_bodega, id_usuario)
VALUES
(1, 'entrada', 25, 1200, 'Carga inicial de arroz', 1, 1, 1),
(2, 'entrada', 8, 4500, 'Carga inicial de pollo', 2, 1, 1),
(3, 'entrada', 40, 900, 'Carga inicial de lechuga', 3, 1, 1),
(4, 'entrada', 60, 1300, 'Carga inicial de bebidas', 4, 1, 1);

INSERT INTO pedido (id_pedido, numero_pedido, fecha_compromiso, fecha_entrega, observaciones, costo_estimado, margen_objetivo, precio_estimado, id_cliente, id_evento, id_estado_pedido, id_usuario_responsable)
VALUES
(1, 'PED-0001', CURRENT_DATE + 20, CURRENT_DATE + 20, 'Pedido de prueba para cumpleaños familiar.', 450000, 30, 650000, 1, 1, 1, 1),
(2, 'PED-0002', CURRENT_DATE + 30, CURRENT_DATE + 30, 'Pedido de prueba para cena empresa.', 980000, 30, 1400000, 2, 2, 2, 1);

INSERT INTO historial_pedido (id_historial_pedido, id_pedido, id_estado_anterior, id_estado_nuevo, observacion, id_usuario)
VALUES
(1, 1, NULL, 1, 'Pedido creado en sistema.', 1),
(2, 2, NULL, 1, 'Pedido creado en sistema.', 1),
(3, 2, 1, 2, 'Pedido confirmado por cliente.', 1);

INSERT INTO detalle_pedido (id_detalle_pedido, id_pedido, tipo_detalle, id_ficha_tecnica, cantidad, costo_unitario, precio_unitario)
VALUES
(1, 1, 'ficha_tecnica', 1, 6, 57000, 85000),
(2, 1, 'ficha_tecnica', 2, 6, 18000, 28000),
(3, 2, 'ficha_tecnica', 1, 12, 57000, 85000),
(4, 2, 'ficha_tecnica', 2, 12, 18000, 28000);

INSERT INTO cotizacion (id_cotizacion, id_pedido, costo_insumos, costo_personal, costo_transporte, otros_costos, costo_total, margen_objetivo, precio_sugerido, estado, observacion, id_usuario)
VALUES
(1, 1, 300000, 90000, 40000, 20000, 450000, 30, 650000, 'vigente', 'Cotización demo cumpleaños familiar.', 1),
(2, 2, 680000, 180000, 80000, 40000, 980000, 30, 1400000, 'vigente', 'Cotización demo cena empresa.', 1);

INSERT INTO venta (id_venta, id_pedido, total, estado, observacion)
VALUES (1, 2, 1400000, 'registrada', 'Venta demo asociada a pedido confirmado.');

INSERT INTO factura (id_factura, id_venta, numero_factura, monto_total, estado)
VALUES (1, 1, 'INT-0001', 1400000, 'emitida');

INSERT INTO pago (id_pago, id_factura, monto, metodo_pago, estado, observacion)
VALUES (1, 1, 700000, 'transferencia', 'parcial', 'Abono inicial demo.');

INSERT INTO checklist_montaje (id_checklist, id_pedido, item, estado, observaciones, id_usuario)
VALUES
(1, 2, 'Confirmar cantidad de mesas', 'pendiente', NULL, 1),
(2, 2, 'Verificar mantelería', 'pendiente', NULL, 1),
(3, 2, 'Confirmar transporte y despacho', 'pendiente', NULL, 1);

INSERT INTO incidencia (id_incidencia, id_pedido, id_usuario, descripcion, foto_url, estado)
VALUES (1, 2, 1, 'Incidencia demo: falta confirmar acceso al lugar.', NULL, 'abierta');

INSERT INTO auditoria (id_auditoria, id_usuario, modulo, accion, tabla_afectada, id_registro_afectado, descripcion)
VALUES
(1, 1, 'sistema', 'CARGA_INICIAL', 'varias_tablas', NULL, 'Carga inicial de datos demo.'),
(2, 1, 'pedido', 'CREAR_PEDIDO', 'pedido', 1, 'Pedido demo PED-0001 creado.'),
(3, 1, 'pedido', 'CREAR_PEDIDO', 'pedido', 2, 'Pedido demo PED-0002 creado.');

-- ===============================================================
-- 15. AJUSTE DE SECUENCIAS DESPUÉS DE INSERTAR IDS EXPLÍCITOS
-- ===============================================================

SELECT setval(pg_get_serial_sequence('rol', 'id_rol'), COALESCE((SELECT MAX(id_rol) FROM rol), 1), true);
SELECT setval(pg_get_serial_sequence('permiso', 'id_permiso'), COALESCE((SELECT MAX(id_permiso) FROM permiso), 1), true);
SELECT setval(pg_get_serial_sequence('usuario', 'id_usuario'), COALESCE((SELECT MAX(id_usuario) FROM usuario), 1), true);
SELECT setval(pg_get_serial_sequence('representante_legal', 'id_representante_legal'), COALESCE((SELECT MAX(id_representante_legal) FROM representante_legal), 1), true);
SELECT setval(pg_get_serial_sequence('cliente', 'id_cliente'), COALESCE((SELECT MAX(id_cliente) FROM cliente), 1), true);
SELECT setval(pg_get_serial_sequence('evento', 'id_evento'), COALESCE((SELECT MAX(id_evento) FROM evento), 1), true);
SELECT setval(pg_get_serial_sequence('pedido', 'id_pedido'), COALESCE((SELECT MAX(id_pedido) FROM pedido), 1), true);
SELECT setval(pg_get_serial_sequence('historial_pedido', 'id_historial_pedido'), COALESCE((SELECT MAX(id_historial_pedido) FROM historial_pedido), 1), true);
SELECT setval(pg_get_serial_sequence('proveedor', 'id_proveedor'), COALESCE((SELECT MAX(id_proveedor) FROM proveedor), 1), true);
SELECT setval(pg_get_serial_sequence('insumo', 'id_insumo'), COALESCE((SELECT MAX(id_insumo) FROM insumo), 1), true);
SELECT setval(pg_get_serial_sequence('ficha_tecnica', 'id_ficha_tecnica'), COALESCE((SELECT MAX(id_ficha_tecnica) FROM ficha_tecnica), 1), true);
SELECT setval(pg_get_serial_sequence('receta', 'id_receta'), COALESCE((SELECT MAX(id_receta) FROM receta), 1), true);
SELECT setval(pg_get_serial_sequence('detalle_preparacion', 'id_detalle_preparacion'), COALESCE((SELECT MAX(id_detalle_preparacion) FROM detalle_preparacion), 1), true);
SELECT setval(pg_get_serial_sequence('detalle_pedido', 'id_detalle_pedido'), COALESCE((SELECT MAX(id_detalle_pedido) FROM detalle_pedido), 1), true);
SELECT setval(pg_get_serial_sequence('cotizacion', 'id_cotizacion'), COALESCE((SELECT MAX(id_cotizacion) FROM cotizacion), 1), true);
SELECT setval(pg_get_serial_sequence('bodega', 'id_bodega'), COALESCE((SELECT MAX(id_bodega) FROM bodega), 1), true);
SELECT setval(pg_get_serial_sequence('inventario', 'id_inventario'), COALESCE((SELECT MAX(id_inventario) FROM inventario), 1), true);
SELECT setval(pg_get_serial_sequence('movimiento_inventario', 'id_movimiento'), COALESCE((SELECT MAX(id_movimiento) FROM movimiento_inventario), 1), true);
SELECT setval(pg_get_serial_sequence('venta', 'id_venta'), COALESCE((SELECT MAX(id_venta) FROM venta), 1), true);
SELECT setval(pg_get_serial_sequence('factura', 'id_factura'), COALESCE((SELECT MAX(id_factura) FROM factura), 1), true);
SELECT setval(pg_get_serial_sequence('pago', 'id_pago'), COALESCE((SELECT MAX(id_pago) FROM pago), 1), true);
SELECT setval(pg_get_serial_sequence('checklist_montaje', 'id_checklist'), COALESCE((SELECT MAX(id_checklist) FROM checklist_montaje), 1), true);
SELECT setval(pg_get_serial_sequence('incidencia', 'id_incidencia'), COALESCE((SELECT MAX(id_incidencia) FROM incidencia), 1), true);
SELECT setval(pg_get_serial_sequence('auditoria', 'id_auditoria'), COALESCE((SELECT MAX(id_auditoria) FROM auditoria), 1), true);

COMMIT;

-- ===============================================================
-- CONSULTAS RÁPIDAS DE VALIDACIÓN
-- ===============================================================
-- SELECT COUNT(*) AS total_regiones FROM region;
-- SELECT COUNT(*) AS total_comunas FROM comuna;
-- SELECT COUNT(*) AS total_paises FROM pais;
-- SELECT * FROM usuario;
-- SELECT p.numero_pedido, c.nombre AS cliente, e.nombre_evento, ep.nombre_estado
-- FROM pedido p
-- JOIN cliente c ON c.id_cliente = p.id_cliente
-- LEFT JOIN evento e ON e.id_evento = p.id_evento
-- JOIN estado_pedido ep ON ep.id_estado_pedido = p.id_estado_pedido;
